---
    - name: Installation Script
      hosts: sas
      tasks:
      - name: Get installation file
        git:
          repo: 'https://github.com/dornxxl/jumpstart.git'
          dest: {{ ansible_env.HOME }}