---
    - name: Installation Script
      hosts: sas
      tasks:
      - name: Get installation file
        git:
          repo: 'https://github.com/OICCIT/oicgw-jumpvm.git'
          dest: '{{ ansible_env.HOME }}/jumpstart'